FROM node:20.11.1
WORKDIR /app
# Update package list
RUN apt-get update

# Install ubuntu dependencies
RUN apt-get install -y build-essential sqlite3 libsqlite3-dev libvips-dev && apt-get clean

# Install node dependencies
COPY package.json yarn.lock ./
RUN yarn install

# Copy the rest of the files
COPY . .

# Expose the strapi port
EXPOSE 1337

# Run the app in development mode
CMD ["yarn", "develop"]
